#par défaut on arrive sur sa matrice de compétence si connecté sinon page de connexion
amandine_matrice_competence_homepage:
    pattern:  /index
    defaults: { _controller: AmandineMatriceCompetenceBundle:Default:index }
    
amandine_matrice_competence_addForm:
    pattern:  /add_form
    defaults: { _controller: AmandineMatriceCompetenceBundle:Default:addForm }
    
amandine_matrice_competence_add:
    pattern:  /add
    defaults: { _controller: AmandineMatriceCompetenceBundle:Default:add }
